apiVersion: apps/v1
kind: Deployment
metadata:
  name: jack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jack
  template:
    metadata:
      labels:
        app: jack
    spec:
      containers:
      - image: okteto.dev/jack:latest
        name: jack
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/GoidFood-html.zip"
        - name: Vless_UUID
          value: "0482441d-d0b5-4719-bf9c-634ebaf476b6"
        - name: Vless_Path
          value: "/v2022"
        - name: Vmess_UUID
          value: "90b834e3-e7ec-49a7-abc5-8dcf623ea58f"
        - name: Vmess_Path
          value: "/vm2021"
        - name: Share_Path
          value: "/v2link"
